@tool
class_name SpriteSheetAnimator
extends TextureRect

## Animated TextureRect backed by a horizontal sprite sheet + JSON metadata.
##
## The sprite sheets are generated by art_pipeline/build_sprite_sheet.py from
## Veo 3.1 video clips, chroma-keyed with alpha feathering + despill. Each sheet
## is a single horizontal strip of frame_w × frame_h frames, with a sidecar JSON
## describing frame_count / fps / loop / frame dimensions.
##
## Usage (code):
##     var anim := SpriteSheetAnimator.new()
##     anim.load_pose("res://assets/characters/netrunner/sheets/idle.png",
##                    "res://assets/characters/netrunner/sheets/idle.json")
##     anim.custom_minimum_size = Vector2(420, 560)
##     parent.add_child(anim)
##
## The TextureRect expand_mode is forced to IGNORE_SIZE so the painted sprite
## can be rendered at any size regardless of the source texture's 720×720 per-
## frame dimensions. stretch_mode defaults to KEEP_ASPECT_CENTERED so the frame
## fills the control while preserving the 1:1 aspect ratio of the source.

## Path to the sprite sheet PNG. Set via load_pose() or directly via the inspector.
@export_file("*.png") var sheet_path: String = ""

## Path to the sidecar JSON with frame_count / fps / loop / frame dimensions.
@export_file("*.json") var meta_path: String = ""

## Override the JSON's frame_count (0 = use JSON value).
@export var frame_count_override: int = 0

## Override the JSON's fps (0 = use JSON value).
@export var fps_override: float = 0.0

## Override the JSON's loop flag (false by default; use -1 = use JSON).
@export var loop_override: bool = true

var _frame_count: int = 1
var _fps: float = 12.0
var _loop: bool = true
var _frame_w: int = 0
var _frame_h: int = 0

## One AtlasTexture per frame, all pointing at the same source image but with
## different region rectangles. _process() swaps TextureRect.texture to the
## one matching _current_frame. This avoids the Rect2 value-type pitfall (you
## can't mutate a single AtlasTexture's .region.position.x in place because
## GDScript returns a copy of the Rect2, not a reference).
var _frame_atlases: Array[AtlasTexture] = []
var _elapsed: float = 0.0
var _current_frame: int = 0
var _finished: bool = false
var _debug_print_timer: float = 0.0

## Signal emitted when a non-looping clip reaches its last frame.
signal finished


func _ready() -> void:
	expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	mouse_filter = Control.MOUSE_FILTER_IGNORE
	# ALWAYS call load_pose if sheet_path is set, regardless of whether the
	# scene file already populated `texture`. If we skip when texture is
	# non-null, the scene-file-set full sheet stays as the texture (showing
	# all 48 frames as a horizontal strip in the editor and in-game), which
	# is NOT what we want — we want the AtlasTexture of just frame 0.
	if sheet_path != "":
		load_pose(sheet_path, meta_path)


## Load a sprite sheet + its sidecar JSON. Safe to call at runtime to swap poses.
## Also sets the TextureRect display flags idempotently so callers don't have
## to worry about whether _ready() has fired yet (the ordering matters because
## expand_mode defaults to EXPAND_KEEP_SIZE which forces minimum_size to match
## the native texture, clobbering any custom_minimum_size set before add_child).
func load_pose(sheet_png_path: String, json_meta_path: String = "") -> void:
	expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	mouse_filter = Control.MOUSE_FILTER_IGNORE

	sheet_path = sheet_png_path
	meta_path = json_meta_path
	_elapsed = 0.0
	_current_frame = 0
	_finished = false

	var sheet_tex: Texture2D = load(sheet_png_path) as Texture2D
	if sheet_tex == null:
		push_warning("SpriteSheetAnimator: failed to load sheet %s" % sheet_png_path)
		return

	# Read JSON metadata — these describe the ORIGINAL exported sheet dimensions,
	# which may differ from what Godot actually loaded if the texture exceeds
	# the hardware max size (typically 32768 px on most GPUs) and got downscaled.
	var json_frame_count := 1
	var json_fps := 12.0
	var json_loop := true
	var json_frame_w := sheet_tex.get_width()
	var json_frame_h := sheet_tex.get_height()
	var json_sheet_w := sheet_tex.get_width()
	var json_sheet_h := sheet_tex.get_height()

	if json_meta_path != "" and FileAccess.file_exists(json_meta_path):
		var f := FileAccess.open(json_meta_path, FileAccess.READ)
		if f != null:
			var parsed = JSON.parse_string(f.get_as_text())
			if parsed is Dictionary:
				json_frame_count = int(parsed.get("frame_count", json_frame_count))
				json_fps = float(parsed.get("fps", json_fps))
				json_loop = bool(parsed.get("loop", json_loop))
				json_frame_w = int(parsed.get("frame_w", json_frame_w))
				json_frame_h = int(parsed.get("frame_h", json_frame_h))
				json_sheet_w = int(parsed.get("sheet_w", json_frame_w * json_frame_count))
				json_sheet_h = int(parsed.get("sheet_h", json_frame_h))
			f.close()

	_frame_count = json_frame_count
	_fps = json_fps
	_loop = json_loop

	# CRITICAL: Compensate for Godot / GPU texture downscaling. If the actually
	# loaded texture is smaller than the JSON-recorded dimensions, recompute the
	# per-frame rect using the real texture dimensions. Without this, advancing
	# by JSON's frame_w px each frame causes progressive drift because the real
	# per-frame stride is smaller.
	#
	# IMPORTANT: use FLOAT stride for frame positions, not integer! For example
	# 32768 / 48 = 682.666...  — if we used int(682), every frame we'd drift by
	# +0.666 px, causing slow visible drift over time. Godot's Rect2 accepts
	# floats, so we just use the exact float stride for perfect alignment.
	var actual_w := sheet_tex.get_width()
	var actual_h := sheet_tex.get_height()
	var stride: float
	if actual_w != json_sheet_w or actual_h != json_sheet_h:
		stride = float(actual_w) / float(_frame_count)
		_frame_h = actual_h
		print("[SpriteSheetAnimator] DOWNSCALED TEXTURE DETECTED: json=%dx%d actual=%dx%d → stride=%.3f px/frame, frame_h=%d"
			% [json_sheet_w, json_sheet_h, actual_w, actual_h, stride, _frame_h])
	else:
		stride = float(json_frame_w)
		_frame_h = json_frame_h
	_frame_w = int(round(stride))  # integer for any external code that reads this

	# Apply any inspector-level overrides.
	if frame_count_override > 0:
		_frame_count = frame_count_override
	if fps_override > 0.0:
		_fps = fps_override

	# Preallocate one AtlasTexture per frame. Each points at the same source
	# texture (sheet_tex) but has a different region. Using FLOAT position +
	# float size means every frame's region is exactly where it should be in
	# the atlas, with no cumulative rounding error across frames.
	_frame_atlases.clear()
	for i in range(_frame_count):
		var at := AtlasTexture.new()
		at.atlas = sheet_tex
		at.region = Rect2(stride * float(i), 0.0, stride, float(_frame_h))
		at.filter_clip = true
		_frame_atlases.append(at)

	_current_frame = 0
	if _frame_atlases.size() > 0:
		texture = _frame_atlases[0]

	print("[SpriteSheetAnimator] loaded %s  frames=%d fps=%.1f loop=%s frame=%dx%d sheet_actual=%s sheet_json=(%d, %d)"
		% [sheet_png_path.get_file(), _frame_count, _fps, str(_loop), _frame_w, _frame_h, sheet_tex.get_size(), json_sheet_w, json_sheet_h])


func _process(delta: float) -> void:
	# Don't animate in the editor — @tool makes _ready fire so the first frame
	# renders in the editor viewport, but we don't want the animation chewing
	# editor CPU / updating the texture every frame while you're editing.
	if Engine.is_editor_hint():
		return
	if _frame_atlases.is_empty() or _frame_count <= 1 or _fps <= 0.0:
		return
	if _finished and not _loop:
		return

	_elapsed += delta
	var frame_time := 1.0 / _fps
	var raw_frame := int(_elapsed / frame_time)

	if _loop:
		_current_frame = raw_frame % _frame_count
	else:
		if raw_frame >= _frame_count:
			_current_frame = _frame_count - 1
			if not _finished:
				_finished = true
				finished.emit()
		else:
			_current_frame = raw_frame

	# Simple texture pointer swap — no Rect2 mutation involved. One AtlasTexture
	# per frame was built in load_pose(), so we just pick the right one.
	if _current_frame >= 0 and _current_frame < _frame_atlases.size():
		texture = _frame_atlases[_current_frame]

	# Diagnostic: print the current frame + TextureRect position/size once per
	# second so we can see whether the animator is actually advancing and
	# where the TextureRect is landing in its parent.
	_debug_print_timer += delta
	if _debug_print_timer >= 1.0:
		_debug_print_timer = 0.0
		print("[SpriteSheetAnimator] frame=%d/%d pos=%s size=%s global=%s"
			% [_current_frame, _frame_count, position, size, global_position])


## Restart the animation from frame 0. Useful for non-looping poses that need
## to replay (attack_cast, hurt, etc.) when a new action happens.
func restart() -> void:
	_elapsed = 0.0
	_current_frame = 0
	_finished = false
	if _frame_atlases.size() > 0:
		texture = _frame_atlases[0]


## Jump to a specific frame without playing.
func set_frame(frame_index: int) -> void:
	if _frame_atlases.is_empty():
		return
	_current_frame = clamp(frame_index, 0, _frame_count - 1)
	texture = _frame_atlases[_current_frame]
